### ISSUE TITLE
Ignore generic types

### ISSUE THREAD

**Issue by palsivertsen** [butuzov/ireturn#37]
`ireturn` should ignore generic type parameters.

I get an error when using `ireturn` on this code:
```go
package example

type Map[K comparable, V any] map[K]V

func (m Map[K, V]) Get(key K) V { return m[key] }
```
![image](https://user-images.githubusercontent.com/11890143/161926131-9e5f4acd-968e-40eb-b7fc-9286a03138e1.png)

`golangci-lint has version 1.45.2 built from 8bdc4d3f on 2022-03-24T11:51:26Z`

**Comment by butuzov** [comment]
Any changes will be done only after war, as I am in active service right
now. It’s more important.

**Comment by palsivertsen** [comment]
Stay strong!

**Comment by iwata** [comment]
@butuzov Any progress?

**Comment by butuzov** [comment]
@iwata well...we took some lands back, more to go. As for this feature, no wasn't using editor since 25th february as I am at war. Man i wish to back to coding, but there are more important things when you country trying to survive.

**Comment by palsivertsen** [comment]
I believe this is still an issue.

**Comment by mitar** [comment]
Also an issue for me with golangci-lint 1.54.2.

**Comment by butuzov** [comment]
You can now build it from sources, and i will release new version as soon as go1.22 releases and I be alive till that momemnt.
