### ISSUE TITLE
Security error reported by sum.golang.org

### ISSUE THREAD

**Issue by etkecc** [butuzov/ireturn#69]
When trying to install golang-ci lint from source:

```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
```

The following error appears:

```
go: downloading github.com/butuzov/ireturn v0.2.1
../../../../go/pkg/mod/github.com/golangci/golangci-lint@v1.55.1/pkg/golinters/ireturn.go:6:2: github.com/butuzov/ireturn@v0.2.1: verifying module: checksum mismatch
	downloaded: h1:QXLHriOCzRI8VN9JPhfDcaaxg3TMFD46n1Pq6Wf5zEw=
	sum.golang.org: h1:w5Ks4tnfeFDZskGJ2x1GAkx5gaQV+kdU3NKNr3NEBzY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by butuzov** [comment]
Thank you. This is tottaly my fault, i did recreate tag instead of deprectation, after CI release failed.  

I will release new version soon with fixes.

**Comment by ldez** [comment]
@butuzov can you create a tag maybe without fixes?
I can use the hash inside golangci-lint but I prefer using a tag.

**Comment by butuzov** [comment]
Created https://github.com/butuzov/ireturn/releases/tag/v0.2.2 , @ldez I will create PR to bump version

**Comment by ldez** [comment]
you don't need to create a PR, the bot will handle that.

**Comment by butuzov** [comment]
Got it.  Thank you for bumping me, almost miss it (5 min task was in my todo for about a week or so).
