### ISSUE TITLE
False positive for generic constraints

### ISSUE THREAD

**Issue by abemedia** [butuzov/ireturn#85]
I'm getting a false positive where there's a generic interface constraint. 

```go
type optValue[T any] interface {
	Get() (v T, ok bool)
}

type optValuePtr[T any, P optValue[T]] interface {
	*P
	SetTo(v T)
}

// ToOpt converts a pointer to a value to an Opt* value.
func ToOpt[R optValue[A], A any, P optValuePtr[A, R]](v *A) (res R) { // <- ToOpt returns generic interface (R)
	if v != nil {
		P.SetTo(&res, *v)
	}
	return res
}
```

In theory one could use an interface e.g. `ToOpt[myOptValueInterface](v)`, and in a perfect world I'd like that to fail linting, however the generic function itself does not violate anything as it could just as well be called with a concrete type.

The way I'm using it is as follows:

```go
type OptString struct {
	Value string
	Set   bool
}

func (os *OptString) SetTo(s string) {
	os.Value = s
	os.Set = true
}

func (os OptString) Get() (string, bool) {
	return os.Value, os.Set
}

func foo()  {
	v := "bar"
	res := ToOpt[OptString](&v)
	// do something with res
}

**Comment by butuzov** [comment]
This is with `0.3.0`? Just ignore generrics...

**Comment by butuzov** [comment]
Try 
- next version (`v1.56`) of [`golangci-lint`](https://github.com/golangci/golangci-lint), once its released (its suppose tobe today, but there is one blocker on official docker image side).
- or try now with bare `ireturn@v0.3.0` (from today's release)

in both cases you need to specify your tolerance for generics, you your case if you using `allow` list - explicitly specify `generics`, of if you are using `reject` list- remove `generics` from there. 

Feel free to reopen if i miss something important.

**Comment by abemedia** [comment]
Just updated to new golangci-lint and all fixed now. Thank you!
